Market/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

import Market

app_name = 'Market'


urlpatterns = [
    # market/ or market/index/
    url(r'^$', views.index, name='index'),
    # market/item/54/
    url(r'^item/(?P<item_c>[0-9]+)/$', views.item_details, name='item_details'),

    # Create
    url(r'addItem/$', views.CreateItem.as_view(), name='create_item'),
    url(r'addDeal/$', views.CreateDeal.as_view(), name='create_Deal'),

    # Delete
    url(r'Deal/(?P<pk>[0-9]+)/delete/$', views.DeleteDeal.as_view(), name='delete_deal'),
#     url(r'deleteItem/(?P<pk>[0-9]+)/$', views.DeleteItem.as_view(), name='delete_item'),

]

valemobiWebProject2017/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Market import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^market/',include(urls)),
]

Market/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Deal(models.Model):
    id = models.AutoField(primary_key=True)
    qtd = models.CharField(max_length=3)
    deal_item = models.ForeignKey('Item', on_delete=models.CASCADE)
    COMPRA = 'Compra'
    VENDA = 'Venda'
    DEAL_TYPE_CHOICES = (
        (VENDA , 'V'),
        (COMPRA , 'C'),

    )
    deal_type = models.CharField(
        max_length=6,
        choices=DEAL_TYPE_CHOICES,
        default=VENDA,
    )

    def get_absolute_url(self):
        return reverse('Market:index')
    def __str__(self):
        return 'Deal Type: ' + self.deal_type + ' | Item: ' \
               + self.deal_item.item_name + ' | Quantity: ' + str(self.qtd)


class Item(models.Model):
    item_code = models.AutoField(primary_key=True, max_length=20)
    item_name = models.CharField(max_length=500)
    item_price = models.DecimalField(max_digits=40, decimal_places=2)
    i_item_type = models.CharField(max_length=50, default='None')

    def get_absolute_url(self):
        return reverse('Market:index')

    def __str__(self):
        return ' | Name: ' \
               + self.item_name + ' | Type: ' + self.i_item_type + \
               ' | Price: ' + str(self.item_price)


        # class Item_type(models.Model):
        #     item_type_char = models.CharField(max_length=1, primary_key=True)
        #     item_type_ds = models.CharField(max_length=50)
        #
        #     def __str__(self):
        #         return self.item_type_char + ": " + self.item_type_ds
        #
        # class Deal_type(models.Model):
        #     deal_type_char = models.CharField(max_length=1, primary_key=True)
        #     deal_type_ds = models.CharField(max_length=50)
        #
        #     def __str__(self):
        #         return self.deal_type_char + ': ' + self.deal_type_ds

Market/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse
from .models import Deal,Item
from django.views.generic import CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy


def index(request):
    all_deals = Deal.objects.all()
    all_items= Item.objects.all()
    context = {
        'all_deals' : all_deals
        ,'all_items' : all_items
    }

    return render(request , 'Market/index.html' , context)

def item_details(request, item_c):
        return HttpResponse(
            '<h1>'
            'Details for Item: ' + str(item_c) +
            '</h1>'

        )

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_price','i_item_type']

class CreateDeal(CreateView):
    model = Deal
    fields = ['deal_item', 'deal_type', 'qtd']

class DeleteDeal(DeleteView):
    model = Deal
    success_url = reverse_lazy('Market:index')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

# Not implemented Yet =(
#
# class DeleteItem(DeleteView):
#     model = Item
#     success_url = reverse_lazy('Market:index')
#
# class UpsateItem(UpdateView):
#     model = Item
#     fields = ['item_name','item_price','i_item_type']
#
# class UpdateDeal(UpdateView):
#     model = Deal
#     fields = ['deal_item', 'deal_type', 'qtd']

Market/templates/Market/deal_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Deals</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Market/style.css' %}">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

</head>

<body>

<div id="addDeal" class="{#modal fade bs-example-modal-sm#}" tabindex="-1"
     role="dialog"                                 #}
     aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><a
                        href="{% url 'Market:index' %}">×</a></button>
                <h3 class="modal-title" id="mySmallModalLabel">Add Deal</h3>
            </div>
            <div class="modal-body width">
                <div class="form-group">
                    <div class="'row">
                        <form action="#" method="POST">
                            {% csrf_token %}
                            <form action="" method="POST" id="item_form">
                                {% csrf_token %}
                                {% include 'Market/form-template.html' %}
                                <div class="form-group"></div>
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default">Submit</button>


                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>

Market/templates/Market/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
			
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag}}</label>
		<div class="  col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

Market/templates/Market/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Deals</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Market/style.css' %}">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

</head>
<body>

<div class="container custom-height">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading c-list">
                <span class="title">Deals</span>
                <ul class="pull-right c-controls">
                    <li><a href="{% url 'Market:create_Deal' %}" data-toggle="tooltip" data-placement="top"
                           title="Add Deal"><i class="glyphicon glyphicon-plus">Deal</i></a></li>
                    <li><a href="{% url 'Market:create_item' %}" data-toggle="tooltip" data-placement="top"
                           title="Add Item"><i class="glyphicon glyphicon-plus">Item</i></a></li>


                </ul>
            </div>

        </div>
        <ul class="list-group" id="contact-list">
            {% if all_deals %}
                {% for deal in all_deals %}
                    <li class="list-group-item">
                        <div class="col-xs-12 col-sm-9">
                                <span class="name">
                                    Deal: {{ deal.id }}
                                    <a href="{% url 'Market:delete_deal' deal.id %}">
                                        <span class="glyphicon small glyphicon-trash"></span>
                                    </a>
                                </span><br/>
                            <span class=""><h4> <a>Item: {{ deal.deal_item }}</h4> </span>
                            <span class=""><h4> Tipo:{{ deal.deal_type }}</h4> </span>
                            <span class=""><h4> Qtd:{{ deal.qtd }}</h4> </span>

                        </div>
                        <div class="clearfix"></div>
                    </li>
                {% endfor %}
            {% else %}
            {% endif %}

        </ul>
    </div>
</div>
</div>
</body>
</html>

Market/templates/Market/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Item</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Market/style.css' %}">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

</head>

<body>
<div id="addItem" class="{#modal fade bs-example-modal-sm#}" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true"><a href="{% url 'Market:index' %}">×</a></button>
                <h3 class="modal-title" id="mySmallModalLabel">Add Item</h3>
            </div>
            <div class="modal-body width">
                <div class="form-group">
                    <div class="'row">
                        <form action="" method="POST" id="item_form">
                            {% csrf_token %}
                            {% include 'Market/form-template.html' %}
                            <div class="form-group"></div>
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>